services:
  # 前端服务
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - CI=false
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - flowminder-network

  # 后端服务
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - ./data/projects:/app/projects
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/flowminder
      - PORT=5000
      - PROJECTS_DIR=/app/projects
    networks:
      - flowminder-network

  # 数据库服务
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - flowminder-network
    environment:
      - MONGO_INITDB_DATABASE=flowminder

networks:
  flowminder-network:
    driver: bridge 