services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      cache_from:
        - flowminder-backend:latest
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: flowminder-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - backend-modules:/usr/local/lib/python3.9/site-packages
    environment:
      - DATABASE_URL=sqlite:///data/flowminder.db
      - DEFAULT_PROJECTS_DIR=/app/data/projects
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - flowminder-network
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 512M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      cache_from:
        - flowminder-frontend:latest
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: flowminder-frontend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_started
    environment:
      - REACT_APP_API_URL=http://backend:8000/api/v1
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
      - FAST_REFRESH=true
    command: npm start
    networks:
      - flowminder-network
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  backend-modules:

networks:
  flowminder-network:
    driver: bridge 