version: '3'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/data
    environment:
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8000
      - DATABASE_URL=sqlite:///./flowminder.db
    command: uvicorn app.api.api:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    
  sync:
    build:
      context: ./sync
      dockerfile: Dockerfile
    volumes:
      - ./sync:/app
      - ./data:/data
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend 