name: Laguna
description: ""
nodes:
  - id: 67da3aeb75049ed27e04bcc5
    type: mainNode
    position:
      x: 0
      y: 0
    data:
      title: TSENS
      status: in_progress
      filePath: tsens.md
edges: []
