name: Laguna
description: ""
nodes:
  - id: 67da3aeb75049ed27e04bcc5
    type: mainNode
    position:
      x: 0
      y: 0
    data:
      title: TSENS
      status: in_progress
      filePath: tsens.md
  - id: 67da3d4a5e711d4a12a7aa84
    type: mainNode
    position:
      x: 0
      y: 0
    data:
      title: LDO
      status: in_progress
      filePath: ldo.md
  - id: 67da41783e784926341f67f7
    type: taskNode
    position:
      x: 0
      y: 0
    data:
      title: tsens readme
      status: in_progress
      filePath: tsens_readme.md
edges:
  - id: e67da3aeb75049ed27e04bcc5-67da41783e784926341f67f7
    source: 67da3aeb75049ed27e04bcc5
    target: 67da41783e784926341f67f7
